### ISSUE TITLE
Project Planning

### ISSUE THREAD

**Issue by solomon-b** [BebeSparkelSparkel/biparsing#2]
Do we want to work on the project design using github issues or keep things on slack for now? 

It would be neat to put together a sort of 'white paper' spec in a markdown or org file to help nail down the scope of the project and the sub-tasks we should each work on.

**Comment by TheMatten** [comment]
We can create channel on Zulip to preserve whatever discussion we may have.

**Comment by BebeSparkelSparkel** [comment]
I think it would be nice to keep everything in one place as much as possible just so that new users and contributors have an easy time finding all the relevant docs.

**Comment by BebeSparkelSparkel** [comment]
Definitely not slack since that disappears.

I like your idea of a "white paper"

@TheMatten do you think the advantages of Zulip outweigh the advantage of the search capabilities that github offers?

**Comment by TheMatten** [comment]
I find real-time communication with more lightweight topics easier than responding to emails. Plus, history of https://funprog.zulipchat.com is publicly available at https://funprog.srid.ca.

**Comment by solomon-b** [comment]
I'm cool with Zulip so long as conversations there result in documentation here. I can volunteer to help with documentation.

**Comment by TheMatten** [comment]
I've created https://funprog.zulipchat.com/#narrow/stream/Biparsing and invited people I've found.

**Comment by masaeedu** [comment]
I spent a couple hours trying to write up the central concept, but it's turned into a huge essay and I'm not sure it makes anything much clearer. Would anyone be interested in just doing a call to go over the basic idea?

**Comment by BebeSparkelSparkel** [comment]
Absolutely!

**Comment by BebeSparkelSparkel** [comment]
What would you suggest hosting this meeting on?

**Comment by BebeSparkelSparkel** [comment]
@ssbothwell Thanks for documenting!
